apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: neanias-status-page
  name: neanias-status-page-svc
spec:
  ports:
  - port: 5000
    name: uwsgi
    protocol: TCP
    targetPort: 5000
  - port: 80
    name: http
    protocol: TCP
    targetPort: 80
  selector:
    app: neanias-status-page


---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: neanias-status-page
  name: neanias-status-page-nginx-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: neanias-status-page

