apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: FIXME
  name: neanias-ci-status-page-role
rules:
- apiGroups:
  - '*'
  resourceNames:
  - neanias-status-page
  resources:
  - deployments
  verbs:
  - update
  - patch
  - get