apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    upstream uwsgicluster {
      server neanias-status-page-svc:5000;
    }

    server {
        listen 80;
        server_name localhost;

        location / {
            include uwsgi_params;
            uwsgi_pass uwsgicluster;
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: neanias-status-page
  name: neanias-status-page
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neanias-status-page
  template:
    metadata:
      labels:
        app: neanias-status-page
    spec:
      containers:
        - image: nginx
          name: nginx-neanias-status-page
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
              readOnly: true
        - image: gitlab.neanias.eu:5050/monitoring-neanias/status-page:latest
          name: neanias-status-page
          envFrom:
            - secretRef:
                name: status-page-secret
          ports:
            - containerPort: 5000
      imagePullSecrets:
        - name: neanias-registry
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf
status: {}
