kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: neanias-ci-status-page-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: neanias-ci-status-page-role
subjects:
- kind: ServiceAccount
  name: neanias-ci-status-page
  namespace: FIXME
